### ISSUE TITLE
Program needs an icon

### ISSUE THREAD

**Issue by scottmc** [raefaldhia/Maps#1]
This application needs an HVIF icon.  This will be a GCI task of it's own.

**Comment by scottmc** [comment]
Seems there is already one that fits our needs for this application.  Grab the HVIF icon for maps from this page, and add it to the .rdef file.  Be sure to add a credit to Michele Frau (Zumi) in the .rdef header file.
http://zumi.xoom.it/myhaiku/miscellaneous/index.html

Here's the .rdef file for BurnItNow which shows how to add the HVIF icon into the file.
https://github.com/HaikuArchives/BurnItNow/blob/master/Source/BurnItNow.rdef

**Comment by scythx** [comment]
Icon added in 56fbdd17d1905bc07df8924968513a5b422fa630.
