### ISSUE TITLE
Crash when you click on empty search results.

### ISSUE THREAD

**Issue by scottmc** [raefaldhia/Maps#17]
I get a seg fault error if I click on an empty search results box.

**Comment by EppMouse** [comment]
Hi. I fixes this bug. This repaired version.
[Maps-master.zip](https://github.com/raefaldhia/Maps/files/1537192/Maps-master.zip)

**Comment by scythx** [comment]
Hi @EppMouse sorry to inform you that another student already fixed the issue here: https://github.com/raefaldhia/Maps/pull/22

Would you like to pick another issue in this repository?

**Comment by scythx** [comment]
#22 Merged, thanks.
